CREATE TABLE resident_vulnerabilities (
    uprn                                bigint generated by default as identity not null primary key,
    date_created                        timestamp,
    health_condition_or_disability      boolean,
    receives_council_tax_support        boolean,
    asc_cases                           integer,
    csc_cases                           integer,
    living_in_temporary_accomodation    boolean,
    low_income                          boolean,
    child_with_send                     boolean,
    single_parent                       boolean,
    learning_disability                 boolean
);
