CREATE TABLE resident_vulnerabilities (
    uprn                                bigint generated by default as identity not null primary key,
    dateCreated                         timestamp,
    healthConditionOrDisability         boolean,
    receivesCouncilTaxReduction         boolean,
    ascCases                            integer,
    cscCases                            integer,
    livingInTemporaryAccomodation       boolean,
    lowIncome                           boolean,
    childWithSEND                       boolean,
    singleParent                        boolean,
    learningDisability                  boolean,
);
